"""
Reads historical metric values from the Excel monitoring logs (already
generated by excel_writer.py each cycle), for use in dashboard trend charts.
"""

import os
import glob
import openpyxl

from utils.paths import BASE_DIR

REPORTS_DIR = os.path.join(BASE_DIR, "reports")


def read_metric_history(metric_name: str, days: int = 5) -> list[dict]:
    if not os.path.isdir(REPORTS_DIR):
        return []

    day_dirs = sorted(glob.glob(os.path.join(REPORTS_DIR, "*")))[-days:]
    points = []

    for d in day_dirs:
        xlsx_path = os.path.join(d, "SAP_BASIS_Monitoring.xlsx")
        if not os.path.exists(xlsx_path):
            continue
        try:
            wb = openpyxl.load_workbook(xlsx_path, data_only=True)
            ws = wb["History"] if "History" in wb.sheetnames else wb.active
            rows = list(ws.iter_rows(values_only=True))
            if not rows:
                continue
            headers = rows[0]
            ts_idx = headers.index("Timestamp")
            metric_idx = headers.index("Metric")
            value_idx = headers.index("Value")

            for row in rows[1:]:
                if row[metric_idx] == metric_name and row[value_idx] is not None:
                    points.append({"timestamp": str(row[ts_idx]), "value": row[value_idx]})
        except Exception:
            continue

    return points