systems:
- name: CENTOR_QAS
  sap_system_id: QAS
  client: '100'
  language: EN
  has_gui_access: true
  connection_name: ${QAS_SAP_CONNECTION_NAME}
  username: ${QAS_SAP_USERNAME}
  password: ${QAS_SAP_PASSWORD}
  has_os_access: false
  rfc:
    ashost: ${QAS_RFC_HOST}
    sysnr: ${QAS_RFC_SYSNR}
    client: ${QAS_RFC_CLIENT}
    username: ${QAS_RFC_USER}
    password: ${QAS_RFC_PASSWORD}
    language: EN
- name: PRD
  client: '100'
  language: EN
  has_gui_access: true
  has_os_access: false
  sap_system_id: PRD
  connection_name: centaur system
  username: basis2
  password: ${PRD_SAP_PASSWORD}
  rfc:
    ashost: 10.1.0.193
    sysnr: '00'
    client: '100'
    username: basis2
    password: ${PRD_RFC_PASSWORD}
    language: EN
  smtp_host: smtp.gmail.com
  smtp_port: '587'
  smtp_username: sarodevishal247@gmail.com
  smtp_password: ${PRD_SMTP_PASSWORD}
  sender_email: sarodevishal347@gmail.com
- name: SARLOHA QAS
  client: '500'
  language: EN
  has_gui_access: true
  has_os_access: false
  sap_system_id: QA1
  connection_name: SARLOHA QAS
  username: basis
  password: ${SARLOHA_QAS_SAP_PASSWORD}
  rfc:
    ashost: 172.22.1.127
    sysnr: '00'
    client: '500'
    username: basis
    password: ${SARLOHA_QAS_RFC_PASSWORD}
    language: EN
- name: SARLOHA PRD
  client: '500'
  language: EN
  has_gui_access: true
  has_os_access: false
  sap_system_id: DB1
  connection_name: SARLOHA PRD
  username: basis
  password: ${SARLOHA_PRD_SAP_PASSWORD}
  rfc:
    ashost: 172.22.1.123
    sysnr: '00'
    client: '500'
    username: basis
    password: ${SARLOHA_PRD_RFC_PASSWORD}
    language: EN
- name: CARFOUR QAS
  client: '800'
  language: EN
  has_gui_access: true
  has_os_access: false
  sap_system_id: CAQ
  connection_name: CARFOUR QAS
  username: CAQ_admin
  password: ${CARFOUR_QAS_SAP_PASSWORD}
  rfc:
    ashost: 172.28.202.213
    sysnr: '00'
    client: '800'
    username: CAQ_admin
    password: ${CARFOUR_QAS_RFC_PASSWORD}
    language: EN
  smtp_host: smtp.gmail.com
  smtp_port: '587'
  smtp_username: sarodevishal247@gmail.com
  smtp_password: ${CARFOUR_QAS_SMTP_PASSWORD}
  sender_email: sarodevishal347@gmail.com
  alert_receivers: sarodevishal347@gmail.com
  alert_receivers_cc: vishal.sarode@infrabeat.com
- name: PS4
  client: '500'
  language: EN
  has_gui_access: true
  has_os_access: false
  sap_system_id: PS4
  connection_name: PS4
  username: ps4_admin
  password: ${PS4_SAP_PASSWORD}
  rfc:
    ashost: 172.28.202.31
    sysnr: '00'
    client: '500'
    username: ps4_admin
    password: ${PS4_RFC_PASSWORD}
    language: EN
  alert_receivers: sarodevishal347@gmail.com
