from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILES = {
    "packaging/systemd/infrabeatops.service": '[Unit]\nDescription=InfraBeatOps SAP Basis Monitoring\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nWorkingDirectory=/opt/infrabeatops\nEnvironmentFile=-/opt/infrabeatops/.env\nExecStart=/opt/infrabeatops/venv/bin/uvicorn dashboard.app:app --host 0.0.0.0 --port 8000\nRestart=on-failure\nRestartSec=10\nTimeoutStopSec=30\nKillSignal=SIGINT\nUser=infrabeatops\nGroup=infrabeatops\n\n[Install]\nWantedBy=multi-user.target\n',
    "packaging/windows/start_infrabeatops.ps1": '$ErrorActionPreference = "Stop"\n$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)\nSet-Location $Root\nif (-not (Test-Path "$Root\\venv\\Scripts\\python.exe")) {\n    throw "Python virtual environment not found at $Root\\venv"\n}\n& "$Root\\venv\\Scripts\\python.exe" -m uvicorn dashboard.app:app --host 0.0.0.0 --port 8000\n',
    "packaging/windows/start_infrabeatops.cmd": '@echo off\nsetlocal\ncd /d "%~dp..\\.."\nif not exist "venv\\Scripts\\python.exe" (\n  echo Python virtual environment not found.\n  exit /b 1\n)\nvenv\\Scripts\\python.exe -m uvicorn dashboard.app:app --host 0.0.0.0 --port 8000\n',
    "packaging/OPERATIONS.md": '# InfraBeatOps 8.4 — Deployment & Operations\n\n## Windows\n\nFrom the project root:\n\n    venv\\Scripts\\activate\n    python -m uvicorn dashboard.app:app --host 0.0.0.0 --port 8000\n\nFor packaged deployment, use `packaging\\build.bat` and the existing Inno Setup\ninstaller. Keep `.env` and `config\\systems.yaml` out of source control.\n\nThe packaged launcher currently binds to `127.0.0.1` by default. Do not expose\nthe dashboard directly to an untrusted network without an authenticated or\nrestricted reverse proxy.\n\n## SLES/Linux\n\nInstall the project under `/opt/infrabeatops`, create a dedicated\n`infrabeatops` user, create the virtual environment, and install\n`requirements.txt`.\n\nCopy `packaging/systemd/infrabeatops.service` to:\n\n    /etc/systemd/system/infrabeatops.service\n\nThen:\n\n    sudo systemctl daemon-reload\n    sudo systemctl enable --now infrabeatops\n    sudo systemctl status infrabeatops\n\nLogs:\n\n    journalctl -u infrabeatops -f\n\nHealth:\n\n    curl http://127.0.0.1:8000/healthz\n    curl http://127.0.0.1:8000/readyz\n\n## Configuration and secrets\n\nDo not commit `.env` or `config/systems.yaml`. Use `.env.example` as the\ntemplate and manage real credentials through your secret-management process.\n\nAI is optional. If the configured provider is unavailable, deterministic\nmonitoring remains authoritative and continues.\n\n## Backup and recovery\n\nBack up configuration and operational state required by your retention policy:\n`.env` through secure secret backup, `config/systems.yaml`,\n`dashboard/snapshots/`, incident/intelligence persistence, and required reports.\n\nDo not back up `venv/`, caches, `__pycache__/`, or build artifacts.\n\nAfter a crash/restart, verify `/healthz`, then `/readyz`, then confirm scheduler\nstatus and the next monitoring cycle.\n\n## Scheduler\n\nThe current dashboard scheduler has a 60-second startup grace period and runs\nan automatic monitoring cycle every 15 minutes.\n',
    "packaging/DEPLOYMENT.md": '# InfraBeatOps deployment\n\n## Windows\n\nUse the existing `packaging\\build.bat` and Inno Setup flow. Test the generated\nexecutable from `dist` before creating the installer.\n\n## SLES/Linux\n\nUse `packaging/systemd/infrabeatops.service` with a dedicated unprivileged\nservice account. Keep `.env` and `config/systems.yaml` outside source control.\n\nVerify after deployment:\n\n    curl http://127.0.0.1:8000/healthz\n    curl http://127.0.0.1:8000/readyz\n\nThe scheduler starts after a 60-second grace period and runs every 15 minutes.\n',
    "tests/test_deployment_readiness.py": 'from pathlib import Path\n\nROOT = Path(__file__).resolve().parents[1]\n\ndef test_systemd_service_restarts_on_failure():\n    text = (ROOT / "packaging/systemd/infrabeatops.service").read_text(encoding="utf-8")\n    assert "Restart=on-failure" in text\n    assert "RestartSec=10" in text\n\ndef test_systemd_service_is_unprivileged():\n    text = (ROOT / "packaging/systemd/infrabeatops.service").read_text(encoding="utf-8")\n    assert "User=infrabeatops" in text\n    assert "Group=infrabeatops" in text\n\ndef test_windows_launcher_uses_uvicorn():\n    text = (ROOT / "packaging/windows/start_infrabeatops.ps1").read_text(encoding="utf-8")\n    assert "uvicorn dashboard.app:app" in text\n\ndef test_operations_scheduler_documentation_is_current():\n    text = (ROOT / "packaging/OPERATIONS.md").read_text(encoding="utf-8")\n    assert "60-second startup grace period" in text\n    assert "every 15 minutes" in text\n\ndef test_deployment_does_not_claim_two_hour_scheduler():\n    text = (ROOT / "packaging/DEPLOYMENT.md").read_text(encoding="utf-8").lower()\n    assert "2-hour scheduler" not in text\n    assert "15 minutes" in text\n',
}

for rel, content in FILES.items():
    target = ROOT / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")

print("Milestone 8.4 applied safely.")
