from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / 'dashboard' / 'static' / 'index.html'
text = HTML.read_text(encoding='utf-8')

if 'data-theme-toggle' not in text:
    css = '''<style>\n  html[data-theme="light"] {\n    --bg:#f4f6f8; --sidebar:#ffffff; --card:#ffffff; --card-hover:#f8fafc;\n    --border:#e2e6eb; --text:#17202a; --muted:#5f6b78; --muted-dim:#8a95a3;\n    --red:#dc2626; --red-dim:rgba(220,38,38,0.10);\n    --green:#16a34a; --green-dim:rgba(22,163,74,0.10);\n    --amber:#d97706; --amber-dim:rgba(217,119,6,0.10);\n    --gray:#6b7280; --gray-dim:rgba(107,114,128,0.10);\n  }\n  html[data-theme="light"] .evidence-item, html[data-theme="light"] input { background:#f8fafc; }\n  html[data-theme="light"] .ai-box { color:#334155; }\n  .theme-toggle { padding:7px 10px; border:1px solid var(--border); background:var(--card); color:var(--text); border-radius:8px; cursor:pointer; font-weight:700; font-size:12px; }\n  .intel-grid { display:grid; grid-template-columns:minmax(0,1.25fr) minmax(260px,.75fr); gap:16px; }\n  .intel-score { display:flex; align-items:center; gap:18px; }\n  .intel-ring { width:76px; height:76px; border-radius:50%; display:grid; place-items:center; font-size:19px; font-weight:900; background:conic-gradient(var(--red) var(--score,0%), var(--border) 0); position:relative; flex-shrink:0; }\n  .intel-ring::after { content:""; position:absolute; inset:8px; border-radius:50%; background:var(--card); }\n  .intel-ring span { position:relative; z-index:1; }\n  .signal-list { display:grid; gap:9px; }\n  .signal-row { display:flex; justify-content:space-between; gap:12px; padding:10px 0; border-bottom:1px solid var(--border); font-size:12px; }\n  .signal-row:last-child { border-bottom:0; }\n  .signal-strength { font-weight:800; }\n  .finding { padding:9px 11px; background:var(--card-hover); border:1px solid var(--border); border-radius:8px; font-size:12px; margin-bottom:8px; }\n  @media (max-width: 1000px) { .sidebar{width:205px}.content{padding:24px}.stat-strip{grid-template-columns:repeat(2,1fr)} .intel-grid{grid-template-columns:1fr} }\n  @media (max-width: 720px) { body{display:block}.sidebar{position:sticky;top:0;z-index:50;width:100%;height:auto;padding:10px 12px;border-right:0;border-bottom:1px solid var(--border)} .brand{padding:0 4px 8px}.sidebar .nav-section-label,.sidebar-footer{display:none}.sidebar .nav-item{display:inline-flex;margin:0 2px;padding:8px}.main{width:100%}.topbar{padding:12px 16px}.content{padding:18px 14px 42px}.greeting{font-size:25px}.stat-strip{grid-template-columns:1fr 1fr;gap:10px}.stat-card{padding:14px}.two-col{grid-template-columns:1fr}.landscape-grid{grid-template-columns:1fr}.header-row{align-items:flex-start}.topbar-right .avatar{display:none}.detail-panel .two-col{grid-template-columns:1fr} }\n'''
    text = text.replace('<style>\n', css, 1)
    top = '<div class="topbar-right">\n      <div class="live-dot-wrap">'
    repl = '<div class="topbar-right">\n      <button class="theme-toggle" data-theme-toggle onclick="toggleTheme()" aria-label="Toggle theme">☀ Light</button>\n      <div class="live-dot-wrap">'
    text = text.replace(top, repl, 1)

if 'id="operationalIntelligence"' not in text:
    anchor = '<div class="section detail-panel" id="detailPanel">'
    block = '''<div class="section" id="operationalIntelligence">\n      <div class="section-head"><div><div class="section-title">Operational intelligence</div><div class="section-sub">Baseline, recurrence and fused signals · advisory only</div></div></div>\n      <div class="intel-grid">\n        <div class="list-card"><div class="intel-score"><div class="intel-ring" id="intelRing"><span id="intelScore">--</span></div><div><div class="section-title" style="font-size:14px" id="intelSignal">No signal</div><div class="section-sub" id="intelSummary">Select a system to inspect operational intelligence.</div></div></div><div style="margin-top:18px" id="intelFindings"><div class="empty">No findings.</div></div></div>\n        <div class="list-card"><div class="section-title" style="font-size:13px;margin-bottom:10px">Signals</div><div class="signal-list" id="intelSignals"><div class="empty">No signals.</div></div></div>\n      </div>\n    </div>\n\n'''
    text = text.replace(anchor, block + anchor, 1)

old = '''  systemStatuses = {};\n  await Promise.all(allSystems.map(async s => {\n    const r = await fetch("/api/status/" + encodeURIComponent(s.name));\n    systemStatuses[s.name] = await r.json();\n  }));'''
new = '''  systemStatuses = {};\n  await Promise.all(allSystems.map(async s => {\n    try {\n      const r = await fetch("/api/systems/" + encodeURIComponent(s.name) + "/overview");\n      if (!r.ok) throw new Error("Overview request failed: " + r.status);\n      systemStatuses[s.name] = { ...(await r.json()), available: true };\n    } catch (err) {\n      console.warn("Overview unavailable for " + s.name, err);\n      systemStatuses[s.name] = { system:s.name, client:s.client, available:false, overall_status:"UNKNOWN", metrics:[], incidents:[], events:[], operational_intelligence:null, ai_analysis:null };\n    }\n  }));'''
if old in text:
    text = text.replace(old, new, 1)

if 'function renderOperationalIntelligence()' not in text:
    insert = '''\nfunction renderOperationalIntelligence() {\n  const data = selectedSystem ? systemStatuses[selectedSystem] : null;\n  const intel = data && data.operational_intelligence;\n  const signal = document.getElementById("intelSignal"), summary = document.getElementById("intelSummary"), scoreEl = document.getElementById("intelScore"), ring = document.getElementById("intelRing"), findings = document.getElementById("intelFindings"), signals = document.getElementById("intelSignals");\n  if (!intel) { const fallback = {overall_status:"UNKNOWN"}; signal.textContent="No signal"; summary.textContent="Insufficient or unavailable intelligence data."; scoreEl.textContent="--"; ring.style.setProperty("--score","0%"); findings.innerHTML='<div class="empty">No findings.</div>'; signals.innerHTML='<div class="empty">No signals.</div>'; return; }\n  const score=Number(intel.score||0), pct=Math.max(0,Math.min(100,Math.round(score*100)));\n  signal.textContent=intel.overall_signal||"UNKNOWN"; summary.textContent=intel.explanation||"Fused operational intelligence from available evidence."; scoreEl.textContent=pct+"%"; ring.style.setProperty("--score",pct+"%");\n  const fs=intel.key_findings||[]; findings.innerHTML=fs.length?fs.slice(0,5).map(x=>'<div class="finding">'+escapeHtml(String(x))+'</div>').join(""):'<div class="empty">No findings.</div>';\n  const ss=intel.signals||[]; signals.innerHTML=ss.length?ss.slice(0,8).map(s=>'<div class="signal-row"><span><b>'+escapeHtml(String(s.category||s.metric||"Signal"))+'</b><br><span style="color:var(--muted)">'+escapeHtml(String(s.summary||""))+'</span></span><span class="signal-strength">'+Math.round(Number(s.strength||0)*100)+'%</span></div>').join(""):'<div class="empty">No signals.</div>';\n}\nfunction escapeHtml(value){const d=document.createElement("div");d.textContent=value;return d.innerHTML;}\nfunction toggleTheme(){const root=document.documentElement;const next=root.dataset.theme==="light"?"dark":"light";root.dataset.theme=next;localStorage.setItem("infrabeatops-theme",next);updateThemeButton();}\nfunction updateThemeButton(){const b=document.querySelector("[data-theme-toggle]");if(b)b.textContent=document.documentElement.dataset.theme==="light"?"◐ Dark":"☀ Light";}\n(function initTheme(){document.documentElement.dataset.theme=localStorage.getItem("infrabeatops-theme")||"dark";})();\n'''
    text = text.replace('function showToast(msg) {', insert + '\nfunction showToast(msg) {', 1)

text = text.replace('  renderDetail();\n  loadTrend(name);', '  renderDetail();\n  renderOperationalIntelligence();\n  loadTrend(name);', 1)
text = text.replace('  } else if (selectedSystem) {\n    renderDetail();\n  }', '  } else if (selectedSystem) {\n    renderDetail();\n    renderOperationalIntelligence();\n  }', 1)
text = text.replace('setGreeting();\nsetInterval(setGreeting, 30000);', 'setGreeting();\nupdateThemeButton();\nsetInterval(setGreeting, 30000);', 1)
HTML.write_text(text, encoding='utf-8')
print('Milestone 7.1 applied safely.')
