from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core.config_loader import get_monitoring_tasks
from reporting.system_paths import system_evidence_root


def _load_existing_index(path: Path) -> list[dict]:
    if not path.exists():
        return []

    try:
        payload = json.loads(
            path.read_text(encoding="utf-8")
        )
    except (OSError, json.JSONDecodeError):
        return []

    return payload if isinstance(payload, list) else []


def _record_time(record: dict) -> str:
    """
    Return the record's finished time for latest-record selection.
    """
    return str(
        record.get("finished_at")
        or record.get("started_at")
        or ""
    )


def _latest_records(records: list[dict]) -> list[dict]:
    """
    Keep only the latest real record for every T-code.

    We deliberately do NOT merge screenshot files across executions.
    """

    latest: dict[str, dict] = {}

    for record in records:
        if not isinstance(record, dict):
            continue

        tcode = str(
            record.get("tcode") or ""
        ).strip().upper()

        if not tcode:
            continue

        current = latest.get(tcode)

        if current is None:
            latest[tcode] = record
            continue

        if _record_time(record) > _record_time(current):
            latest[tcode] = record

    return list(latest.values())


def _task_order() -> list[str]:
    """
    Preserve monitoring_tasks.yaml order.
    """

    return [
        str(task.get("tcode", "")).strip().upper()
        for task in get_monitoring_tasks()
        if str(task.get("tcode", "")).strip()
    ]


def _sort_records(records: list[dict]) -> list[dict]:
    """
    Sort records using monitoring_tasks.yaml order.
    Unknown T-codes are placed at the end.
    """

    order = {
        tcode: index
        for index, tcode in enumerate(_task_order())
    }

    return sorted(
        records,
        key=lambda record: (
            order.get(
                str(record.get("tcode", "")).upper(),
                9999,
            ),
            str(record.get("tcode", "")),
        ),
    )


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Rebuild the evidence index using the latest "
            "real execution record for each T-code."
        )
    )

    parser.add_argument(
        "--system",
        required=True,
    )

    parser.add_argument(
        "--client",
        required=True,
    )

    parser.add_argument(
        "--date",
        required=True,
        help="YYYY-MM-DD",
    )

    args = parser.parse_args()

    date = datetime.strptime(
        args.date,
        "%Y-%m-%d",
    )

    root = system_evidence_root(
        args.system,
        date,
    )

    index_path = root / "evidence_index.json"

    if not index_path.exists():
        raise SystemExit(
            f"No evidence index found: {index_path}"
        )

    existing = _load_existing_index(
        index_path
    )

    if not existing:
        raise SystemExit(
            f"Evidence index is empty: {index_path}"
        )

    # ------------------------------------------------------------------
    # IMPORTANT:
    #
    # We use REAL records already generated by the collector.
    #
    # We do NOT scan screenshots and create synthetic records.
    # This prevents separate monitoring executions from being merged.
    # ------------------------------------------------------------------

    records = []

    for record in existing:

        if not isinstance(record, dict):
            continue

        if str(record.get("system", "")).upper() != args.system.upper():
            continue

        if str(record.get("client", "")) != str(args.client):
            continue

        records.append(record)

    latest = _latest_records(records)

    latest = _sort_records(
        latest
    )

    # ------------------------------------------------------------------
    # Write only the latest record per T-code.
    #
    # Screenshot files are NOT deleted.
    # ------------------------------------------------------------------

    index_path.write_text(
        json.dumps(
            latest,
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    screenshot_count = sum(
        len(record.get("screenshot_paths", []))
        for record in latest
    )

    failed = [
        record
        for record in latest
        if str(record.get("status", "")).lower() == "failed"
    ]

    print(
        f"Rebuilt evidence index: {index_path}"
    )

    print(
        f"Latest T-code records: {len(latest)}"
    )

    print(
        f"Unique T-codes: "
        f"{len(set(record.get('tcode') for record in latest))}"
    )

    print(
        f"Screenshot references: {screenshot_count}"
    )

    print(
        "Failed T-codes:",
        [
            (
                record.get("tcode"),
                record.get("attempts"),
                record.get("status"),
            )
            for record in failed
        ],
    )


if __name__ == "__main__":
    main()